root: true

extends:
- plugin:@mysticatea/es2015

overrides:
- files:
  - src/**/*.js
  - test/**/*.js
  extends: plugin:@mysticatea/+modules
  rules:
    init-declarations: "off"
    "@mysticatea/node/no-unsupported-features/es-syntax":
    - error
    - ignores: [modules]
